### ISSUE TITLE
Consider not starting/ending names with underscores

### ISSUE THREAD

**Issue by wleightond** [codereport/dovekie#1]
I notice that the naming so far is consistent with the other combinator libraries you've worked on, but in the Python case starting a name with an underscore is used to [mark that function as private](https://peps.python.org/pep-0008/#descriptive-naming-styles:~:text=weak%20%E2%80%9Cinternal%20use%E2%80%9D%20indicator). The impact is that `from dovekie import *` does not make everything available to applications trying to use the library.

I do see a few functions that would provide a challenge to name with a different scheme since the underscores are semantically meaningful... the prime example here would be `mod`:
```c++
auto _mod   = [](auto x) { return [x](auto y) { return x % y; }; };
auto mod_   = [](auto x) { return [x](auto y) { return y % x; }; };
auto _mod_  = std::modulus{};
```

**Comment by codereport** [comment]
That is a good point. I asked GPT4 and it suggested:

1. Use Abbreviations or Full Names with Semantic Suffixes or Prefixes
Instead of relying on underscore positioning, consider using abbreviations or full names with clear suffixes or prefixes that carry the semantic weight. For example:
```
_mod could become modL (for Left-modulus) or leftMod.
mod_ could become modR (for Right-modulus) or rightMod.
_mod_ is a standard modulus operation, so it could simply be named mod or stdMod for standard modulus.
```
This approach keeps the naming concise while avoiding the use of underscores as semantic carriers, making the functionality clear through the naming itself.

2. Incorporate Hungarian Notation
Though not universally popular, a form of Hungarian notation could be used to encode the semantic meaning previously carried by underscores. This involves a prefix (or suffix) that hints at the function's behavior or usage.

For example:
```
_mod becomes lmod for left-modulus.
mod_ becomes rmod for right-modulus.
_mod_ remains a challenge but could perhaps be cmod for "classic" or "common" modulus, emphasizing its standard behavior.
```
3. Use a Naming Scheme with Decorative Suffixes
Instead of leading or trailing underscores, consider decorative suffixes that do not conflict with Python's naming conventions but still convey the intended semantics.
```
_mod could become modLeft or modL.
mod_ could become modRight or modR.
_mod_ could be more challenging but could perhaps be modStandard or modStd.
```

**Comment by codereport** [comment]
I am not a huge fan of any of those ⬆️ suggestions so let's try `import dovekie as d` for now and see how I feel about that. It isn't as short as the underscores in all cases and is a bit "noisier" in general but I agree that clashing with idiomatic Python is worse. I pushed the change https://github.com/codereport/dovekie/commit/002b7de32f0dcaaed07873a76da15baa6bb2a7e5
